<?php

function aic_api_menu() {
  $items['api-query/%/%'] = array(
    'page callback' => 'api_query',
    'page arguments' => array(1, 2),
    'access callback' => TRUE,
  );

  $items['api-query-theme/%/%'] = array(
    'page callback' => 'api_query_theme',
    'page arguments' => array(1, 2),
    'access callback' => TRUE,
  );

  $items['api-update-galleries'] = array(
    'page callback' => 'api_gallery_update',
    'access callback' => TRUE,
  );

  $items['admin/settings/aic-api'] = array(
    'title' => 'AIC API module settings',
    'description' => 'Specify the URLs of your API',
    'page callback' => 'drupal_get_form',
	'access callback' => TRUE,
    'page arguments' => array('aic_api_admin'),
    'access arguments' => array('administer aic api settings'),
    'type' => MENU_CALLBACK,
   );

  return $items;
}

function aic_api_cron() {
  api_gallery_update();
  $languages = db_query("SELECT language FROM {languages}");

  foreach($languages as $lang) {
    $l = $lang->language;
    aic_json_page('json', $l);
    aic_json_page('json-on-display', $l);
    aic_json_page('json-off-display', $l);
  }

}

function api_gallery_update() {
  $result = db_query("SELECT nid FROM {node} WHERE type = 'artwork' AND language = 'en' ORDER BY title");

  $output = '';
  
  $l = db_query("
    SELECT language FROM {languages}");

  $languages = array();

  foreach($l as $lang) {
    $languages[] = $lang->language;
  }
  //go through all artwork nodes
  foreach ($result as $r) {
    $node = node_load($r->nid);

    $artwork_query = variable_get('aicapi_artwork_query');
    $gallery_query = variable_get('aicapi_gallery_query');

    if (isset($node->field_object_id['und']) && isset($artwork_query) && isset($gallery_query)) {
      $output .= "<strong>Updating:</strong> ({$node->field_object_id['und'][0]['value']}) " . l($node->title, 'node/' . $node->nid) . "<br><br>";
      //fetching artwork data
      $json = fetch_api_data('id', $node->field_object_id['und'][0]['value']);

      $gallery_id = null;

      foreach ($json as $k => $doc) {
        //finding gallery of artwork
        if (isset($doc->gallery_id)) {
          $gallery_id = $doc->gallery_id;
        }
      }

      //fetching gallery data
      $json2 = fetch_api_data('gallery', $gallery_id);

      foreach ($json2 as $k => $doc) {
        $gallery_id = null;
        $gallery_name = null;
        $map_x = null;
        $map_y = null;
        $floor = null;
        $is_closed = false;

        if (isset($doc->is_closed)) {
          $is_closed = $doc->is_closed;
        }
        if (isset($doc->id)) {
          $gallery_id = $doc->id;
        }
        if (isset($doc->title)) {
          $gallery_name = $doc->title;
        }
        if (isset($doc->latitude)) {
          if (!$is_closed) {
            $map_x = $doc->latitude;
          }
        }
        if (isset($doc->longitude)) {
          if (!$is_closed) {
            $map_y = $doc->longitude;
          }
        }
        if (isset($doc->floor)) {
          $floor = $doc->floor;
        }
        //setting values of artwork fields in CMS
        $node->field_gallery_id['und'][0]['value'] = $gallery_id;
        $node->field_gallery_name['und'][0]['value'] = $gallery_name;
        $node->field_map_x['und'][0]['value'] = $map_x;
        $node->field_map_y['und'][0]['value'] = $map_y;
        $node->field_floor['und'][0]['value'] = $floor;

        node_save($node);
      }
	  
	    // also update translated nodes.
      foreach($languages as $lang) {
        $translated_nid = aic_json_nid_by_lang($node->nid, $lang);
        if ($translated_nid == $node->nid) continue;
        $trans_node = node_load($translated_nid);

        $trans_node->field_gallery_id['und'][0]['value'] = $gallery_id;
        $trans_node->field_gallery_name['und'][0]['value'] = $gallery_name;
        $trans_node->field_map_x['und'][0]['value'] = $map_x;
        $trans_node->field_map_y['und'][0]['value'] = $map_y;
        $trans_node->field_floor['und'][0]['value'] = $floor;
        node_save($trans_node);
        $output .= "<strong>Updating:</strong> ({$node->field_object_id['und'][0]['value']}) " . l($trans_node->title, 'node/' . $trans_node->nid) . "<br><br>";
      }
    }
  }
  cache_clear_all();
  return $output;
}

function api_query_theme($search_type, $search_term) {
  //fetch api data
  $json = fetch_api_data($search_type, $search_term);

  $output = "<br /><br /><a class='button' onclick='jQuery(\"#api-query-results\").html(\"\");'>Clear Results</a>";

  //construct image url
  $base_image_url = variable_get('iiif_image_url');
  $image_specs = '/full/!800,800/0/default.jpg';

    foreach ($json as $k => $doc) {

      $image_url = $base_image_url . $doc->image_id . $image_specs;

      if (isset($image_url) && ($image_url != '')) {
        $table = "<br /><br /><table>";
        $table .= "<tr><th style='width:25%''>Title</th>                 <td id='title_$k'     data-value='{$doc->title}'>{$doc->title}</td></tr>";
        $table .= "<tr><th>Image</th>                 <td id='image_$k'     data-value='{$image_url}'>";
        $table .= "<img src='{$image_url}' width='200' />";
        $table .= "<br />{$image_url}</td></tr>";
        $table .= "<tr><td colspan='2' align='right'><a class='button' onclick='populate_theme_form($k);'>Populate Form</a></td></tr>";
        $table .= "</table>";
      }
      $output .= $table;
    }
  print $output;
}

function api_query($search_type, $search_term) {
  //fetch api data
  $json_array = fetch_api_data($search_type, $search_term);

  $output = "<br /><br /><a class='button' onclick='jQuery(\"#api-query-results\").html(\"\");'>Clear Results</a>";

  //construct image url
  $base_image_url = variable_get('iiif_image_url');
  $image_specs = '/full/!800,800/0/default.jpg';

  foreach ($json_array as $k => $doc) {

    $image_url = $base_image_url . $doc->image_id . $image_specs;

    $table = "<br /><br /><table>";
    $table .= "<tr><th width='25%'>ObjectID</th>  <td id='id_$k' data-value='{$doc->id}'>{$doc->id}</td></tr>";
    $table .= "<tr><th>Title</th>                 <td id='title_$k'     data-value='{$doc->title}'>{$doc->title}</td></tr>";
    $table .= "<tr><th>Image</th>                 <td id='image_$k'     data-value='{$image_url}'>";

    if (isset($image_url) && ($image_url != '')) {
      $table .= "<img src='{$image_url}' width='200' />";
    }

    $table .= "<br />{$image_url}</td></tr>";
    $table .= "<tr><th>Artist</th>            <td id='artist_title_$k'       data-value='{$doc->artist_title}'>{$doc->artist_title}</td></tr>";
    $table .= "<tr><th>Year</th>              <td id='date_$k'              data-value='{$doc->date_display}'>{$doc->date_display}</td></tr>";
    $table .= "<tr><th>Gallery Location</th>  <td id='gallery_$k'           data-value='{$doc->gallery_title}'>{$doc->gallery_title}</td></tr>";
    $table .= "<tr><th>Copyright</th>         <td id='copy_$k'              data-value='{$doc->copyright_notice}'>{$doc->copyright_notice}</td></tr>";

    if ($doc->is_on_view == TRUE) {

      $json2 = fetch_api_data('gallery', $doc->gallery_id);

      foreach ($json2 as $doc2) {

        $table .= "<tr><th>Gallery ID</th>  <td id='gallery_id_$k'   data-value='{$doc2->id}'> {$doc2->id}</td></tr>";
        $table .= "<tr><th>Latitude</th>  <td id='lat_$k'   data-value='{$doc2->latitude}'> {$doc2->latitude}</td></tr>";
        $table .= "<tr><th>Longitude</th> <td id='lon_$k'   data-value='{$doc2->longitude}'>{$doc2->longitude}</td></tr>";
        $table .= "<tr><th>Floor</th>     <td id='floor_$k' data-value='{$doc2->floor}'>    {$doc2->floor}</td></tr>";
        
      }
    }

    $table .= "<tr><td colspan='2' align='right'><a class='button' onclick='populate_artwork_form($k);'>Populate Form</a></td></tr>";
    $table .= "</table>";

    $output .= $table;
    }
  print $output;
}

function fetch_api_data($search_type, $search_term) {
  //get values set in admin/settings/aic-api
  $general_query = variable_get('aicapi_general_query');
  $gallery_query = variable_get('aicapi_gallery_query');
  $artwork_query = variable_get('aicapi_artwork_query');

  if (($search_type == 'title' || $search_type == 'artist_title') && isset($general_query)) {
    //searching by artwork title or artist name
    $dataQuery = array(
      'resources' => 'artworks',
      'from' => 0,
      'size' => 10,
      'fields' => array(
        'id',
        'title',
        'artist_title',
        'date_display',
        'gallery_title',
        'is_on_view',
        'copyright_notice',
        'image_id',
        'gallery_id'
      ),
      'query' => array(
        'match' => array(
          $search_type => array(
            'query' => $search_term,
            'fuzziness' => 'AUTO',
          ),
        )
      )
    );
    $url = $general_query;
  } else if ($search_type == 'id' && isset($artwork_query)) {
    //searching by object id
    $dataQuery = array(
      'ids' => $search_term,
      'limit' => 1,
    );
    $url = $artwork_query;
  } else if ($search_type == 'gallery' && isset($gallery_query)) {
    //searching for gallery
    $dataQuery = array(
      'ids' => $search_term,
      'limit' => 1,
    );
    $url = $gallery_query;
  } else {
    drupal_set_message('There was an error in your query.');
  }
  
  $options = http_build_query($dataQuery);
  $post_options = array(
    'method' => 'POST',
    'data' => $options,
    'headers' => array('Content-Type' => 'application/json'),
  );
  //request for data
  $json = drupal_http_request($url .'?'. $options, $post_options);
  //filtering for correct data
  $json = $json->data;
  $json_data = json_decode($json);
  $json_data = $json_data->data;
  //array check
  $json_array = is_array($json_data) ? $json_data : array($json_data);

  return $json_array;
}

function aic_api_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'aic_theme_node_form') {
    $general_query = variable_get('aicapi_general_query');
    if (isset($general_query)) {
      drupal_add_js(drupal_get_path('module', 'aic_api') .'/aic_api.js', 'file');

      $form['field_background_image_url']['#prefix'] = '
        <strong>Query API:</strong><br /><br />
        <input type="text" id="api-text" name="api-text" style="width:250px; margin-right:10px; border:1px solid #999; font-size: 14px; padding: 3px 5px;" placeholder="Search Terms" /> <br /><br />
        <input type="radio" value="id" id="search_type" name="search_type"/> Object Id &nbsp;&nbsp;&nbsp;&nbsp;
        <input type="radio" value="title" id="search_type" name="search_type" /> Title &nbsp;&nbsp;&nbsp;&nbsp;
        <input type="radio" value="artist_title" id="search_type" name="search_type" /> Artist Name<br /><br />
        <a class="button" href="#" id="query-api-button-theme">Query API</a>

        <div id="api-query-results"></div>
        <br /><br />
      ';
    }
  }

  if ($form_id == 'artwork_node_form') {
    $general_query = variable_get('aicapi_general_query');
    if (isset($general_query)) {

      drupal_add_js(drupal_get_path('module', 'aic_api') .'/aic_api.js', 'file');

      $form['api-integration'] = array(
        '#type' => 'item',
        '#markup' => '

        <strong>Query API:</strong><br /><br />
        <input type="text" id="api-text" name="api-text" style="width:250px; margin-right:10px; border:1px solid #999; font-size: 14px; padding: 3px 5px;" placeholder="Search Terms" /> <br /><br />
        <input type="radio" value="id" id="search_type" name="search_type"/> Object Id &nbsp;&nbsp;&nbsp;&nbsp;
        <input type="radio" value="title" id="search_type" name="search_type" /> Title &nbsp;&nbsp;&nbsp;&nbsp;
        <input type="radio" value="artist_title" id="search_type" name="search_type" /> Artist Name<br /><br />
        <a class="button" href="#" id="query-api-button">Query API</a>

        <div id="api-query-results"></div>
      '
      );

      $form['field_viewing_description']['#description'] = 'foo foo foo';
    }
  }
}

function aic_api_node_presave($node) {
  if (  $node->type == 'artwork') {
    if (isset($node->field_image_url['und']) && isset($node->field_image_url['und'][0]) && ($node->field_image_url['und'][0]['value'] <> '')) {
        $image = file_get_contents($node->field_image_url['und'][0]['value']);
        $filename = $node->field_object_id['und'][0]['value'] . '.jpg';
        $file = file_save_data($image, 'public://' . $filename, FILE_EXISTS_REPLACE);

        $node->field_artwork_image['und'][0] = (array) $file;
        unset($node->field_image_url['und']);
    }
  }

  if (  $node->type == 'aic_theme') {

    if (isset($node->field_background_image_url['und']) && (isset($node->field_background_image_url['und'][0])) && ($node->field_background_image_url['und'][0]['value'] <> '')) {
        $image = file_get_contents($node->field_background_image_url['und'][0]['value']);
        //temporary fix for naming image. Perhaps we should just store the object id and use for filename
        $filename = rand() . '.jpg';
        $file = file_save_data($image, 'public://' . $filename, FILE_EXISTS_REPLACE);

        $node->field_background['und'][0] = (array) $file;
        unset($node->field_background_image_url['und']);
    }
  }
}

function aic_api_admin() {
  $form = array();

  $form['aicapi_artwork_query'] = array(
    '#type' => 'textfield',
    '#title' => t('Artwork query URL'),
    '#default_value' => variable_get('aicapi_artwork_query', ''),
    '#size' => 60,
    '#maxlength' => 256,
    '#description' => t("Enter the artworks' endpoint URL."),
  );

  $form['aicapi_gallery_query'] = array(
    '#type' => 'textfield',
    '#title' => t('Gallery query URL'),
    '#default_value' => variable_get('aicapi_gallery_query', ''),
    '#size' => 60,
    '#maxlength' => 256,
    '#description' => t("Enter the galleries' endpoint URL. "),
  );

  $form['aicapi_general_query'] = array(
    '#type' => 'textfield',
    '#title' => t('Search query URL'),
    '#default_value' => variable_get('aicapi_general_query', ''),
    '#size' => 60,
    '#maxlength' => 256,
    '#description' => t("Enter the search endpoint URL."),
  );

  $form['iiif_image_url'] = array(
    '#type' => 'textfield',
    '#title' => t('IIIF Image Server URL'),
    '#default_value' => variable_get('iiif_image_url', ''),
    '#size' => 60,
    '#maxlength' => 256,
    '#description' => t("Enter base url to IIIF image server."),
  );

  return system_settings_form($form);
}

function aic_api_admin_validate($form, &$form_state) {
  $artwork_query = $form_state['values']['aicapi_artwork_query'];
  if (substr($artwork_query, 0, 7) !== "http://" && substr($artwork_query, 0, 8) !== "https://") {
    form_set_error('aic_artwork_query', t('You must enter a URL.'));
  }

  $gallery_query = $form_state['values']['aicapi_gallery_query'];
  if (substr($gallery_query, 0, 7) !== "http://" && substr($gallery_query, 0, 8) !== "https://") {
    form_set_error('aic_gallery_query', t('You must enter a URL.'));
  }

  $general_query = $form_state['values']['aicapi_general_query'];
  if (substr($general_query, 0, 7) !== "http://" && substr($general_query, 0, 8) !== "https://") {
    form_set_error('aic_general_query', t('You must enter a URL.'));
  }

  $base_image_url = $form_state['values']['iiif_image_url'];
  if (substr($base_image_url, 0, 7) !== "http://" && substr($base_image_url, 0, 8) !== "https://") {
    form_set_error('aic_image_url', t('You must enter a URL.'));
  }
}
